from .acceuilscreen.acceuilview import AcceuilView
from .projetscreen.projetsview import ProjectView
from .ouvragescreen.ouvrageview import OuvrageView
from .createouvragescreen.createouvrageview import CreateOuvrageView
from .editouvragescreen.editouvrageview import EditOuvrageView
from .recapouvragescreen.recapouvrageview import RecapOuvrageView
from .settingscreen.settingview import SettingView
from .aproposcreen.apropoview import ApropoView
from .filtreouvragescreen.filtreouvrageview import FiltreOuvrageView
from .statgeneralscreen.statgeneralview import StatGeneralView
from .statcommunescreen.statcommuneview import StatCommuneView
from .statcantonscreen.statcantonview import StatCantonView
from .statscreen.statview import StatView
from .statparprojetscreen.statparprojetview import StatParProjetView
from .intervaldatescreen.intervaldateview import IntervalDateView
from .archivescreen.archiveview import ArchiveView
